document.write('');
document.write('');
		</div> <!--#content-inside-->');
	</div><!-- #content -->');
	<div class="footer-shadow container">');
		<div class="row">');
			<div class="col-md-12">');
				<img src="https://pokemonfansub.github.io/wp-content/themes/codilight-lite/assets/images/footer-shadow.png" alt="" />');
			</div>');
		</div>');
	</div>');
	<footer id="colophon" class="site-footer" role="contentinfo">');
		<div class="container">');
document.write('');
document.write('');
			<div class="site-info">');
				<p>');
					Copyright &copy; 2026 Pokémon Fansub. All Rights Reserved.				</p>');
				Source Code <a href="https://github.com/pokemonfansub/pokemonfansub.github.io/">Github</a>			</div><!-- .site-info -->');
document.write('');
		</div>');
	</footer><!-- #colophon -->');
</div><!-- #page -->');
document.write('');
<link rel=\'stylesheet\' id=\'responsive-progressbar-style-css\'  href=\'https://pokemonfansub.github.io/wp-content/plugins/responsive-progress-bar/assets/css/style.css?ver=4.2.2\' type=\'text/css\' media=\'all\' />');
document.write('');
<script type=\'text/javascript\' src=\'https://pokemonfansub.github.io/wp-content/plugins/wp-polls/polls-js.js?ver=2.73.7\'></script>');
<script type=\'text/javascript\' src=\'https://pokemonfansub.github.io/wp-content/themes/codilight-lite/assets/js/libs.js?ver=20120206\'></script>');
<script type=\'text/javascript\' src=\'https://pokemonfansub.github.io/wp-content/themes/codilight-lite/assets/js/theme.js?ver=20120206\'></script>');
<script type=\'text/javascript\' src=\'https://pokemonfansub.github.io/wp-content/plugins/responsive-progress-bar/assets/js/responsive-progressbar.js?ver=4.2.2\'></script>');
<script type=\'text/javascript\' src=\'https://cdn.onesignal.com/sdks/OneSignalSDK.js?ver=4.2.2\' async=\'async\'></script>');
document.write('');
</body>');
</html>');
document.write('');
document.write('');
