document.write('');
document.write('');
document.write('		</div> <!--#content-inside-->');
document.write('	</div><!-- #content -->');
document.write('	<div class="footer-shadow container">');
document.write('		<div class="row">');
document.write('			<div class="col-md-12">');
document.write('				<img src="/wp-content/themes/codilight-lite/assets/images/footer-shadow.png" alt="" />');
document.write('			</div>');
document.write('		</div>');
document.write('	</div>');
document.write('	<footer id="colophon" class="site-footer" role="contentinfo">');
document.write('		<div class="container">');
document.write('');
document.write('');
document.write('			<div class="site-info">');
document.write('				<p>');
document.write('					Copyright &copy; 2026 Pokémon Fansub. All Rights Reserved.				</p>');
document.write('				Source Code <a href="https://github.com/pokemonfansub/pokemonfansub.github.io/">Github</a>			</div><!-- .site-info -->');
document.write('');
document.write('		</div>');
document.write('	</footer><!-- #colophon -->');
document.write('</div><!-- #page -->');
document.write('');
document.write('<link rel=\'stylesheet\' id=\'responsive-progressbar-style-css\'  href=\'/wp-content/plugins/responsive-progress-bar/assets/css/style.css?ver=4.2.2\' type=\'text/css\' media=\'all\' />');
document.write('<script type=\'text/javascript\' src=\'/wp-content/plugins/anti-spam/js/anti-spam-3.5.js\'></script>');
document.write('<script type=\'text/javascript\'>');
document.write('/* <![CDATA[ */');
document.write('var title = {"expand":"Expand","collapse":"Collapse"};');
document.write('/* ]]> */');
document.write('</script>');
document.write('<script type=\'text/javascript\' src=\'/wp-content/plugins/inline-spoilers/scripts/inline-spoilers-scripts.js?ver=1.4.1\'></script>');
document.write('<script type=\'text/javascript\' src=\'/wp-content/plugins/wp-polls/polls-js.js?ver=2.73.7\'></script>');
document.write('<script type=\'text/javascript\' src=\'/wp-content/themes/codilight-lite/assets/js/libs.js?ver=20120206\'></script>');
document.write('<script type=\'text/javascript\' src=\'/wp-content/themes/codilight-lite/assets/js/theme.js?ver=20120206\'></script>');
document.write('<script type=\'text/javascript\' src=\'/wp-includes/js/comment-reply.min.js?ver=4.2.2\'></script>');
document.write('<script type=\'text/javascript\' src=\'/wp-content/plugins/responsive-progress-bar/assets/js/responsive-progressbar.js?ver=4.2.2\'></script>');
document.write('<script type=\'text/javascript' src='https://cdn.onesignal.com/sdks/OneSignalSDK.js?ver=4.2.2\' async='async'></script>');
document.write('');
document.write('</body>');
document.write('</html>');
document.write('');
document.write('');
