document.write('<!--<head star>-->');
document.write('<!DOCTYPE html>');
document.write('<html lang="fr-FR">');
document.write('<head>');
document.write('<meta charset="UTF-8">');
document.write('<meta name="viewport" content="width=device-width, initial-scale=1">');
document.write('<link rel="profile" href="http://gmpg.org/xfn/11">');
document.write('<link rel="pingback" href="https://pokemonfansub.alwaysdata.net/xmlrpc.php">');
document.write('<title>Pok&eacute;mon Fansub | Le paradis du VOSTFR</title>');
document.write('<link rel="alternate" type="application/rss+xml" title="Pok&eacute;mon Fansub &raquo; Flux" href="https://pokemonfansub.github.io/rss2.xml" />');
document.write('<link rel="alternate" type="application/rss+xml" title="Pok&eacute;mon Fansub &raquo; Flux des commentaires" href="https://pokemonfansub.github.io/comments-rss2.xml" />');
document.write('		<script type="text/javascript">');
document.write('			window._wpemojiSettings = {"baseUrl":"http:\/\/s.w.org\/images\/core\/emoji\/72x72\/","ext":".png","source":{"concatemoji":"http:\/\/pokemonfansub.github.io\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.2.2"}};');
document.write('			!function(a,b,c){function d(a){var c=b.createElement("canvas"),d=c.getContext&&c.getContext("2d");return d&&d.fillText?(d.textBaseline="top",d.font="600 32px Arial","flag"===a?(d.fillText(String.fromCharCode(55356,56812,55356,56807),0,0),c.toDataURL().length>3e3):(d.fillText(String.fromCharCode(55357,56835),0,0),0!==d.getImageData(16,16,1,1).data[0])):!1}function e(a){var c=b.createElement("script");c.src=a,c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var f,g;c.supports={simple:d("simple"),flag:d("flag")},c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.simple&&c.supports.flag||(g=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",g,!1),a.addEventListener("load",g,!1)):(a.attachEvent("onload",g),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),f=c.source||{},f.concatemoji?e(f.concatemoji):f.wpemoji&&f.twemoji&&(e(f.twemoji),e(f.wpemoji)))}(window,document,window._wpemojiSettings);');
document.write('		</script>');
document.write('		<style type="text/css">');
document.write('img.wp-smiley,');
document.write('img.emoji {');
document.write('	display: inline !important;');
document.write('	border: none !important;');
document.write('	box-shadow: none !important;');
document.write('	height: 1em !important;');
document.write('	width: 1em !important;');
document.write('	margin: 0 .07em !important;');
document.write('	vertical-align: -0.1em !important;');
document.write('	background: none !important;');
document.write('	padding: 0 !important;');
document.write('}');
document.write('</style>');
document.write('<link rel=\'stylesheet\' id=\'wp-polls-css\'  href=\'https://pokemonfansub.github.io/wp-content/plugins/wp-polls/polls-css.css?ver=2.73.7\' type=\'text/css\' media=\'all\' />');
document.write('<style id=\'wp-polls-inline-css\' type=\'text/css\'>');
document.write('.wp-polls .pollbar {');
document.write('	margin: 1px;');
document.write('	font-size: 6px;');
document.write('	line-height: 8px;');
document.write('	height: 8px;');
document.write('	background-image: url(\'https://pokemonfansub.github.io/wp-content/plugins/wp-polls/images/default/pollbg.gif\');');
document.write('	border: 1px solid #c8c8c8;');
document.write('}');
document.write('');
document.write('</style>');
document.write('<link rel=\'stylesheet\' id=\'codilight-lite-google-fonts-css\'  href=\'https://fonts.googleapis.com/css?family=Raleway%3A300%2C400%2C500%2C600%7CMerriweather&#038;subset=latin%2Clatin-ext\' type=\'text/css\' media=\'all\' />');
document.write('<link rel=\'stylesheet\' id=\'codilight-lite-fontawesome-css\'  href=\'https://pokemonfansub.github.io/wp-content/themes/codilight-lite/assets/css/font-awesome.min.css?ver=4.4.0\' type=\'text/css\' media=\'all\' />');
document.write('<link rel=\'stylesheet\' id=\'codilight-lite-style-css\'  href=\'https://pokemonfansub.github.io/wp-content/themes/codilight-lite/style.css?ver=4.2.2\' type=\'text/css\' media=\'all\' />');
document.write('<script type=\'text/javascript\' src=\'https://pokemonfansub.github.io/wp-includes/js/jquery/jquery.js?ver=1.11.2\'></script>');
document.write('<script type=\'text/javascript\' src=\'https://pokemonfansub.github.io/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1\'></script>');
document.write('<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://pokemonfansub.alwaysdata.net/xmlrpc.php?rsd" />');
document.write('<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://pokemonfansub.github.io/wp-includes/wlwmanifest.xml" />');
document.write('<style type="text/css" id="custom-background-css">');
document.write('body.custom-background { background-image: url(\'https://pokemonfansub.github.io/wp-content/uploads/FC3E5A3C-5779-486C-8759-FD0241C285EC.jpeg\'); background-repeat: repeat-y; background-position: top right; background-attachment: fixed; }');
document.write('</style>');
document.write('</head>');
document.write('');
document.write('');
document.write('<body class="home blog custom-background group-blog">');
document.write('<div id="page" class="hfeed site">');
document.write('	<a class="skip-link screen-reader-text" href="#content">Skip to content</a>');
document.write('');
document.write('	<div id="topbar" class="site-topbar">');
document.write('		<div class="container">');
document.write('			<div class="topbar-left pull-left">');
document.write('				<nav id="site-navigation" class="main-navigation" role="navigation">');
document.write('					<span class="home-menu"> <a href="https://pokemonfansub.github.io/" rel="home"><i class="fa fa-home"></i></a></span>');
document.write('					<span class="nav-toggle"><a href="#0" id="nav-toggle">Menu<span></span></a></span>');
document.write('					<ul class="ft-menu">');
document.write('						<li id="menu-item-1907" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1907"><a href="https://pokemonfansub.github.io/phtml/1878.html">&eacute;pisodes</a>');
document.write('<ul class="sub-menu">');
document.write('	<li id="menu-item-3148" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3148"><a href="https://pokemonfansub.github.io/phtml/1878.html">Liste des &eacute;pisodes</a>');
document.write('	<ul class="sub-menu">');
document.write('		<li id="menu-item-3889" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3889"><a href="https://pokemonfansub.github.io/phtml/3848.html">Arc Advanced G&eacute;n&eacute;ration</a></li>');
document.write('		<li id="menu-item-3360" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3360"><a href="https://pokemonfansub.github.io/phtml/3357.html">Arc XY</a></li>');
document.write('		<li id="menu-item-3844" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3844"><a href="https://pokemonfansub.github.io/phtml/3842.html">Arc Sun &#038; Moon</a></li>');
document.write('		<li id="menu-item-4754" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4754"><a href="https://pokemonfansub.github.io/phtml/4751.html">Arc Pocket Monsters 2019</a></li>');
document.write('		<li id="menu-item-7308" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7308"><a href="https://pokemonfansub.github.io/phtml/7306.html">Pok&eacute;mon Horizons</a></li>');
document.write('		<li id="menu-item-4755" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4755"><a href="https://pokemonfansub.github.io/phtml/3560.html">Film 20</a></li>');
document.write('		<li id="menu-item-4756" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4756"><a href="https://pokemonfansub.github.io/phtml/4214.html">Film 21</a></li>');
document.write('		<li id="menu-item-5027" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5027"><a href="https://pokemonfansub.github.io/phtml/5010.html">Film 22</a></li>');
document.write('		<li id="menu-item-6975" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6975"><a href="https://pokemonfansub.github.io/phtml/6953.html">Film 23</a></li>');
document.write('	</ul>');
document.write('</li>');
document.write('	<li id="menu-item-1901" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1901"><a href="https://pokemonfansub.github.io/phtml/1529.html">Rythme de sortie</a></li>');
document.write('	<li id="menu-item-1902" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1902"><a href="http://pokemon-streaming-mix.eklablog.com/">Pok&eacute;mon Streaming</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li id="menu-item-5196" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5196"><a href="https://pokemonfansub.github.io/phtml/5194.html">Streaming</a>');
document.write('<ul class="sub-menu">');
document.write('	<li id="menu-item-5295" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5295"><a href="https://pokemonfansub.github.io/phtml/5293.html">Streaming : Arc Advanced G&eacute;n&eacute;ration</a>');
document.write('	<ul class="sub-menu">');
document.write('		<li id="menu-item-5296" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5296"><a href="https://pokemonfansub.github.io/phtml/5291.html">Streaming : Saison 6</a></li>');
document.write('		<li id="menu-item-5303" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5303"><a href="https://pokemonfansub.github.io/phtml/5298.html">Streaming : Saison 7</a></li>');
document.write('	</ul>');
document.write('</li>');
document.write('	<li id="menu-item-5200" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5200"><a href="https://pokemonfansub.github.io/phtml/5185.html">Streaming : Arc XY</a></li>');
document.write('	<li id="menu-item-5199" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5199"><a href="https://pokemonfansub.github.io/phtml/5191.html">Streaming : Arc XY&#038;Z</a></li>');
document.write('	<li id="menu-item-5215" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5215"><a href="https://pokemonfansub.github.io/phtml/5205.html">Streaming : Arc Sun &#038; Moon</a>');
document.write('	<ul class="sub-menu">');
document.write('		<li id="menu-item-5255" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5255"><a href="https://pokemonfansub.github.io/phtml/5207.html">Streaming : Saison 20</a></li>');
document.write('		<li id="menu-item-5254" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5254"><a href="https://pokemonfansub.github.io/phtml/5208.html">Streaming : Saison 21</a></li>');
document.write('		<li id="menu-item-5253" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5253"><a href="https://pokemonfansub.github.io/phtml/5209.html">Streaming : Saison 22</a></li>');
document.write('	</ul>');
document.write('</li>');
document.write('	<li id="menu-item-5251" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5251"><a href="https://pokemonfansub.github.io/phtml/5245.html">Streaming : Arc PM2019</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li id="menu-item-1899" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1899"><a href="https://pokemonfansub.github.io/phtml/877.html">FAQ</a></li>');
document.write('<li id="menu-item-1900" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1900"><a href="https://pokemonfansub.github.io/phtml/874.html">Staff</a></li>');
document.write('<li id="menu-item-4781" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4781"><a href="https://discord.gg/qcPjqcz">Discord</a></li>');
document.write('<li id="menu-item-4782" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4782"><a href="https://twitter.com/PokeFansub">Twitter</a></li>');
document.write('<li id="menu-item-4783" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4783"><a href="https://www.facebook.com/p0kemonfansub/">Facebook</a></li>');
document.write('					</ul>');
document.write('				</nav><!-- #site-navigation -->');
document.write('			</div>');
document.write('			<div class="topbar-right pull-right">');
document.write('<!--<search>-->');
document.write('			</div>');
document.write('		</div>');
document.write('');
document.write('	</div><!--#topbar-->');
document.write('		<div class="mobile-navigation">');
document.write('				<ul>');
document.write('			<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1907"><a href="https://pokemonfansub.github.io/phtml/1878.html">&eacute;pisodes</a>');
document.write('<ul class="sub-menu">');
document.write('	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-3148"><a href="https://pokemonfansub.github.io/phtml/1878.html">Liste des &eacute;pisodes</a>');
document.write('	<ul class="sub-menu">');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3889"><a href="https://pokemonfansub.github.io/phtml/3848.html">Arc Advanced G&eacute;n&eacute;ration</a></li>');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3360"><a href="https://pokemonfansub.github.io/phtml/3357.html">Arc XY</a></li>');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-3844"><a href="https://pokemonfansub.github.io/phtml/3842.html">Arc Sun &#038; Moon</a></li>');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-4754"><a href="https://pokemonfansub.github.io/phtml/4751.html">Arc Pocket Monsters 2019</a></li>');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7308"><a href="https://pokemonfansub.github.io/phtml/7306.html">Pok&eacute;mon Horizons</a></li>');
document.write('		<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4755"><a href="https://pokemonfansub.github.io/phtml/3560.html">Film 20</a></li>');
document.write('		<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4756"><a href="https://pokemonfansub.github.io/phtml/4214.html">Film 21</a></li>');
document.write('		<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-5027"><a href="https://pokemonfansub.github.io/phtml/5010.html">Film 22</a></li>');
document.write('		<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6975"><a href="https://pokemonfansub.github.io/phtml/6953.html">Film 23</a></li>');
document.write('	</ul>');
document.write('</li>');
document.write('	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1901"><a href="https://pokemonfansub.github.io/phtml/1529.html">Rythme de sortie</a></li>');
document.write('	<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1902"><a href="http://pokemon-streaming-mix.eklablog.com/">Pok&eacute;mon Streaming</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5196"><a href="https://pokemonfansub.github.io/phtml/5194.html">Streaming</a>');
document.write('<ul class="sub-menu">');
document.write('	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5295"><a href="https://pokemonfansub.github.io/phtml/5293.html">Streaming : Arc Advanced G&eacute;n&eacute;ration</a>');
document.write('	<ul class="sub-menu">');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5296"><a href="https://pokemonfansub.github.io/phtml/5291.html">Streaming : Saison 6</a></li>');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5303"><a href="https://pokemonfansub.github.io/phtml/5298.html">Streaming : Saison 7</a></li>');
document.write('	</ul>');
document.write('</li>');
document.write('	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5200"><a href="https://pokemonfansub.github.io/phtml/5185.html">Streaming : Arc XY</a></li>');
document.write('	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5199"><a href="https://pokemonfansub.github.io/phtml/5191.html">Streaming : Arc XY&#038;Z</a></li>');
document.write('	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-5215"><a href="https://pokemonfansub.github.io/phtml/5205.html">Streaming : Arc Sun &#038; Moon</a>');
document.write('	<ul class="sub-menu">');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5255"><a href="https://pokemonfansub.github.io/phtml/5207.html">Streaming : Saison 20</a></li>');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5254"><a href="https://pokemonfansub.github.io/phtml/5208.html">Streaming : Saison 21</a></li>');
document.write('		<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5253"><a href="https://pokemonfansub.github.io/phtml/5209.html">Streaming : Saison 22</a></li>');
document.write('	</ul>');
document.write('</li>');
document.write('	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-5251"><a href="https://pokemonfansub.github.io/phtml/5245.html">Streaming : Arc PM2019</a></li>');
document.write('</ul>');
document.write('</li>');
document.write('<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1899"><a href="https://pokemonfansub.github.io/phtml/877.html">FAQ</a></li>');
document.write('<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1900"><a href="https://pokemonfansub.github.io/phtml/874.html">Staff</a></li>');
document.write('<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4781"><a href="https://discord.gg/qcPjqcz">Discord</a></li>');
document.write('<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4782"><a href="https://twitter.com/PokeFansub">Twitter</a></li>');
document.write('<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-4783"><a href="https://www.facebook.com/p0kemonfansub/">Facebook</a></li>');
document.write('		</ul>');
document.write('			</div>');
document.write('');
document.write('		<header id="masthead" class="site-header" role="banner">');
document.write('		<div class="container">');
document.write('			<div class="site-branding">');
document.write('				<a title="Pok&eacute;mon Fansub" class="site-logo" href="https://pokemonfansub.github.io/" rel="home"><img src="https://pokemonfansub.github.io/wp-content/uploads/bannière.png" alt="Pok&eacute;mon Fansub"></a>			</div><!-- .site-branding -->');
document.write('		</div>');
document.write('	</header>');
document.write('<!-- #masthead -->');
document.write('		<div id="content" class="site-content container right-sidebar">');
document.write('		<div class="content-inside">');
document.write('			<div id="primary" class="content-area">');
	document.write('			<main id="main" class="site-main" role="main">');
document.write('<!--<head end>-->');
document.write('');
document.write('');
