document.write('<div id="secondary" class="widget-area sidebar" role="complementary">');
document.write('');
document.write('<aside id="text-22" class="widget widget_text">			<!--<div class="textwidget"><b>Pour ceux qui ont des pubs en streaming, téléchargez un <a href="https://www.google.com/search?sxsrf=ALeKk03NaXilnz5yJShgeQFs1JWwvRJ_6g%3A1588596515575&ei=Iw-wXpLYIqSTlwT-iLHwDg&q=adblock" target="_blank"><span style="color: #9b2c33;">bloqueur de pub</span></a></b></div>-->');
document.write('		</aside><aside id="text-13" class="widget widget_text">			<div class="textwidget"><img src="https://pokemonfansub.github.io/wp-content/uploads/avancement1.png">');
document.write('<center><b>Pokémon Horizons 123</b></center>');
document.write('<center><iframe width="640" height="180" frameborder="0" src="https://pokemonfansub.github.io/video/Pokemon-Fansub-Pokemon-Horizons-122-VOSTFR-FR-1920x1080-H264-AAC.mp4.html" allowfullscreen></iframe>');
document.write('</center>');
document.write('');
document.write('<div class=\'rprogress-container\'>');
document.write('				<div class=\'rprogress-wrap rprogress\' data-progress-percent=\'30\' data-speed=\'1000\' style=\'background: #94FF97; border-radius: 3px; -moz-border-radius: 3px; -webkit-border-radius: 3px; -o-border-radius: 3px;\'>');
document.write('					<div class=\'rprogress-bar rprogress\' style=\'background: #ccc\'></div><div class=\'rprogress-text\' style=\'color: #333\'>Time</div>');
document.write('				</div>');
document.write('				</div>');
document.write('');
document.write('');
document.write('<a href ="https://pokemonfansub.github.io/phtml/877.html"><img src="https://pokemonfansub.github.io/wp-content/uploads/Sans-titre-11.png"></a>');
document.write('');
document.write('<br />');
document.write('<br /></div>');
document.write('		</aside><aside id="text-14" class="widget widget_text">			<div class="textwidget"><img src="https://pokemonfansub.github.io/wp-content/uploads/Fichier_13.png">');
document.write('<br />');
document.write('<br />');
document.write('<a href="https://mamonofansub65474530.wordpress.com/"><img src="https://mamonofansub65474530.files.wordpress.com/2018/08/banniere-petite.jpg?w=900" width="100"></a><br />');
document.write('');
document.write('<a href="http://teamsynchrofansub.com"><span style="color: #9b2c33;">Synchro Fansub</span></a>');
document.write('<br />');
document.write('');
document.write('');
document.write('</div>');
document.write('		</aside><aside id="text-12" class="widget widget_text">			<div class="textwidget"><img src="https://pokemonfansub.github.io/wp-content/uploads/contact1.png">');
document.write('<br />');
document.write('<br />');
document.write('');
document.write('<img src="https://pokemonfansub.github.io/wp-content/uploads/gmail.png"width=25>');
document.write('staff.pokemonfansub@gmail.com');
document.write('<br />');
document.write('<br />');
document.write('<a />');
document.write('href="https://discord.gg/qcPjqcz"><span style="color: #9b2c33;"> <img src="https://pokemonfansub.github.io/wp-content/uploads/discord.png"width=30> </span></a> <a href="https://discord.gg/qcPjqcz"><span style="color: #9b2c33;">Serveur Discord</span></a>');
document.write('<br />');
document.write('<br />');
document.write('<a href="https://twitter.com/PokeFansub" class="twitter-follow-button" data-show-count="false">Follow @PokeFansub</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+\'://platform.twitter.com/widgets.js\';fjs.parentNode.insertBefore(js,fjs);}}(document, \'script\', \'twitter-wjs\');</script></div>');
document.write('		</aside>		</div><!-- #secondary -->');
document.write('');
